# workflow to enforce style and linting on PR
name: eslint-prettier
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
  
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # Setup npm environment to run tests
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx eslint-config-prettier src/*.ts src/**/*.ts
      - run: npx prettier --check src/*.ts src/**/*.ts
      - run: npx eslint src/*.ts src/**/*.ts
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply eslint and prettier formatting changes
